[font]
size = 15

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"


[window]
opacity = 0.90
decorations= "Full"
startup_mode="Windowed"
dynamic_padding = true
padding = { x = 5, y = 5}

# Causing a bug on macOS
[shell]
program = "/opt/homebrew/bin/tmux"

# [keyboard]
#  bindings = [
#     { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
#  ]

[[hints.enabled]]
regex = "[^ ]+\\.rs:\\d+:\\d+"
command = { program = "nvim" }
mouse = { enabled = false }
