[font]
size = 20

# [font.normal]
# family = "Reddit Mono"
# style = "Regular"

# [font.italic]
# family = "Reddit Mono"
# style = "Italic"

# [font.bold]
# family = "Reddit Mono"
# style = "Bold"

# [font.bold_italic]
# family = "Reddit Mono"
# style = "Bold Italic"


[window]
opacity = 0.9
decorations= "Transparent"
startup_mode="SimpleFullscreen"
dynamic_padding = true
padding = { x = 5, y = 10}

# Causing a bug on macOS
[shell]
program = "/opt/homebrew/bin/tmux"

# [keyboard]
#  bindings = [
#     { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
#  ]

[[hints.enabled]]
regex = "[^ ]+\\.rs:\\d+:\\d+"
command = { program = "nvim" }
mouse = { enabled = false }
